### ISSUE TITLE
[Feature Request] Setting powerline-separator globally

### ISSUE THREAD

**Issue by jdugan6240** [jdugan6240/powerline.kak#10]
As mentioned by @basbebe in issue #9, the `powerline-separator` command only works for the current buffer - any subsequent buffers that are opened remain unchanged. While this behavior is useful for setting a different separator per buffer - say, having separate buffers for .c and .py files, it would be nice to have the option to set this option on a global scale.

**Comment by jdugan6240** [comment]
Here's one option that I would like to propose. Say we added a flag to the powerline-* commands to indicate on which scope the change should take effect - for example, `powerline-separator -global triangle`. This should allow for changes on a global scale while still allowing for the same buffer-level granularity the old system offered.

**Comment by basbebe** [comment]
I personally would find it more useful to set it globally and then leave it to the user to add per-filetype hooks but as your wrote above the use-cases might be different there.

**Comment by jdugan6240** [comment]
Here's the main problem I see with that: say you wish to set the separator for .c files to triangle. You'd put the `powerline-separator triangle` command in a filetype hook to set it. However, if the command set the separator globally, this would mean that all the other buffers you have open would have their separators set as well, defeating the purpose of the filetype hook.

This is why I proposed a system for determining at which scope each command should operate. For per-file options like you describe, the -buffer scope would work without the problems I outlined above.

I hope this makes sense 😉

**Comment by jdugan6240** [comment]
I just realized - after having another look at the main powerline.kak file, it seems that powerline.kak already supports setting the scope of the operation. If you run the following, for example:

`powerline-separator global triangle`,

it will set the powerline separator globally.

I think, after adding this to the README, that this solves your issue. Let me know if you have any problems with it.
