### ISSUE TITLE
[Feature Request] Make lsp module only visible when lsp is enabled

### ISSUE THREAD

**Issue by basbebe** [jdugan6240/powerline.kak#11]
I would find it useful if the lsp module would only be visible when lsp actually was enabled.

I tried putting `powerline-toggle-lsp off` in my powerline config and then `powerline-toggle-lsp on` in the `hook global WinSetOption filetype=(c|cpp|cc|rust|python|java|latex|markdown)` section of my lsp section.

This does only work when a new buffer is loaded, not for the first one.

I guess one could build a hook into the module which checks for the output of `lsp-capabilities` on buffer load, but there might be a better solution?

**Comment by jdugan6240** [comment]
The best solution I can come up with at present is similar to how kak-lsp itself detects if it's already enabled in any given window - try to create a semantic tokens highlighter, and bail if you can't.

Essentially, something like this:

```
try %{
    add-highlighter window/cquery_semhl ranges cquery_semhl
    remove-highlighter window/cquery_semhl
    #Now handle the lsp module
}
```

It's a bit ghetto, but kak-lsp doesn't offer a better way of handling this at present that I know of. I haven't actually tried this, so it may not work the way I want it to, but it's as good a place to start as any.

**Comment by jdugan6240** [comment]
I've committed the above solution. It seems to work on my side, so run `plug-install` on your config to see if it works for you.

**Comment by jdugan6240** [comment]
Also, here's something that may help with the original problem you were having with the first buffer not being affected by your changes:

The original workaround I gave you in the other issue only configures the plugin on the WinDisplay hook, which occurs after the buffer-related hooks IIRC. The following is more in line with what the `defer` keyword does in andreyorst's original plug.kak:

```
plug-old powerline https://github.com/jdugan6240/powerline.kak %{
    hook global ModuleLoaded powerline %{
        #Configure powerline.kak as desired
        powerline-theme gruvbox
    }
    powerline-start
}
```

This should allow you to then use the buffer-based hooks to set different configurations per file type, as before.

**Comment by jdugan6240** [comment]
Since there's been no updates for a few days, and things seem to work fine on my end, I'm going to close this issue. Feel free to reopen if you're still having problems.
