### ISSUE TITLE
Separators not showing as they should

### ISSUE THREAD

**Issue by eko234** [jdugan6240/powerline.kak#4]
i've tried using special fonts for things like vim powerline, using differente terminals, and i don't seem to find a way for the separators to display as they do in the demo, i think the readme should contain some guidline explaining how to make it work.

**Comment by jdugan6240** [comment]
Ok, that's not normal. Depending on what font you're using, there shouldn't be a problem with the separators showing. Admittedly, the readme could be a bit clearer that a powerline-compatible font is required.

Can you tell me what font you're using, and paste your kakrc?

For what it's worth, on my system, I'm using the NotoMono Nerd Font from the Nerd Fonts repository [here](https://github.com/ryanoasis/nerd-fonts) in the Alacritty terminal emulator, and the relevant part of my kakrc is as follows:
```
plug "jdugan6240/powerline.kak" defer powerline %{
    set-option global powerline_format 'lsp git bufname filetype mode_info line_column position'
}
```

**Comment by eko234** [comment]
yup, it was it, i installed the fonts and now it displays properly. thanks.
