### ISSUE TITLE
Part of the git module is still visible on files that are not in git repos

### ISSUE THREAD

**Issue by DERPSQUID9** [jdugan6240/powerline.kak#5]
## Steps to reproduce

1. Create a minimal config file
```
# Source plug.kak
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# The theme I use. I don't know if this shows up in other themes or not, so I'm including it just in case
plug "DERPSQUID9/kakoune-cyberpunk-neon" theme config %{
	colorscheme cyberpunk-neon
}

# My powerline settings
plug "jdugan6240/powerline.kak" defer powerline %{
	set-option global powerline_shorten_bufname short

	# Use my theme for powerline
	powerline-theme cyberpunk-neon
} config %{
	powerline-start
}

```
2. Open kakoune and run `:plug-install<ret>` and quit when it is finished.
3. Open a file that is known to tracked in a git repo to confirm that the git module works. Note its background color. (In my theme, it is purple.)
4. Open a file that is not in a git repo. 

## What should happen

I would expect that the git module would be completely hidden for files that are not tracked by git.

## What happens instead

For files that are not tracked by git, at the end of the powerline prompt, at the point of the bufname module, a small amount of the git module's background color can still be seen.

## Environment information
Kakoune version: Kakoune v2020.09.01
OS version: Manjaro Linux 20.1
`sh` executable version: zsh 5.8

**Comment by jdugan6240** [comment]
Thanks for the detailed report; I am able to reproduce the issue with the steps you've provided. This does seem to show up in other themes, so it's not your theme that's at fault (cool theme, by the way).

The problem appears to be the following: though the 'git branch' output only shows if the 'git branch' command outputs something meaningful, the "set the next background" step happens regardless.

I've just pushed commit [359fe7e541fd44eeb4f7b33d6fce63c22de5397c](https://github.com/jdugan6240/powerline.kak/commit/359fe7e541fd44eeb4f7b33d6fce63c22de5397c) to hopefully fix this. Run `plug-update` on your minimal config to see if the problem has been resolved.

**Comment by DERPSQUID9** [comment]
I just updated it, and while it seems fine on non-git files now, when I open a file in a git repo, the part of the git module's background that was visible on non-git files before is now gone.

**Comment by jdugan6240** [comment]
That's because I made a couple of typos on the line that sets the separator background.

Try again please 😅

**Comment by DERPSQUID9** [comment]
Now it works perfectly. Thank you!
